### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by aashish24** [Kitware/resonanthpc#31]
* Add a project screenshot 
* Few other general details on how to contribute etc. 
* Project team

**Comment by banesullivan** [comment]
Done! I did not add any details on contributing yet because things are still rapidly changing. When we get to a more stable point (after v0 of the CMB interface), I can add a contributing guide.

This isn't nearly as pretty as what the website will be, but it has the content until we get the website live

**Comment by aashish24** [comment]
@banesullivan the update site looks great thanks for doing it. 

@johnkit have a look too, it is looking nice.
