### ISSUE TITLE
Relative links are broken on the website

### ISSUE THREAD

**Issue by banesullivan** [Kitware/resonanthpc#38]
The link at the bottom of the home page for "Meet Our Team" is broken. As well as other relative links.

@jtomeck, I'm not terribly familiar with Jekyll... is there an option to tell it the base URL is `https://kitware.github.io/resonanthpc/` and not `https://kitware.github.io/`

**Comment by jtomeck** [comment]
You can add `baseurl: /resonanthpc` in the _config.yml file, but I'm wondering if just adding `{{ site.baseurl }}/team` in the href for that link would fix the issue.

I think you can because the icons in the "HPC-Enabled Pre- and Post-Processing with Jupyter" section on the homepage are loaded with the baseurl prepended, so obviously it knows the baseurl as `/resonanthpc` already. If you'd like I can go through and take care of all the instances where this is needed once I get some time.
